-- MySQL Script generated by MySQL Workbench
-- Fri Mar 10 15:23:54 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_empregos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_empregos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_empregos` DEFAULT CHARACTER SET utf8 ;
USE `db_empregos` ;

-- -----------------------------------------------------
-- Table `db_empregos`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_empregos`.`tb_usuario` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `foto` VARCHAR(500) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_empregos`.`tb_tema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_empregos`.`tb_tema` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `categoria` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_empregos`.`tb_postagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_empregos`.`tb_postagens` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `texto` VARCHAR(2000) NULL,
  `imagem` VARCHAR(500) NOT NULL,
  `data` DATETIME NOT NULL DEFAULT DEFAULT(getdate()),
  `usuario_id` BIGINT NOT NULL,
  `tema_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_postagens_tb_usuario_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_tb_postagens_tb_tema1_idx` (`tema_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_postagens_tb_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `db_empregos`.`tb_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_postagens_tb_tema1`
    FOREIGN KEY (`tema_id`)
    REFERENCES `db_empregos`.`tb_tema` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
